#!/usr/bin/env python3
"""Scan the LLM Wiki for context gaps and generate targeted interview questions.

Gap types (by priority):
  0. Pending Questions — auto-captured unexpanded preferences/judgments
  1. Stale Concepts    — concept updated date far behind latest source date
  1. Open Questions    — unresolved bullets in concept pages
  2. Thin Pages        — concept/entity pages with < 100 body words
  2. Vague Entities    — entity pages with empty/thin Mentions section
  3. Timeline Gaps     — months with < 5 source entries

Note: Gap type for cross-source contradictions from the spec is intentionally
omitted — it requires LLM semantic understanding, not regex scanning.
"""
from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

WIKI_ROOT = Path(__file__).resolve().parent.parent / "wiki"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_TITLE_RE = re.compile(r'^title:\s*["\']?(.*?)["\']?\s*$', re.MULTILINE)
_UPDATED_RE = re.compile(r'^updated:\s*(\d{4}-\d{2}-\d{2})\s*$', re.MULTILINE)
_SOURCES_RE = re.compile(r'^sources:\s*\[(.*?)\]', re.MULTILINE)
_DATE_PREFIX_RE = re.compile(r"^(?:notion|cc|gem|auto)-(\d{4}-\d{2})")
STALE_THRESHOLD_DAYS = 7


def _read_file(path: Path) -> str | None:
    """Read a file, returning None on any I/O error."""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _strip_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block, body) from a markdown file."""
    m = _FRONTMATTER_RE.match(text)
    if m:
        return m.group(1), text[m.end():]
    return "", text


def _extract_title(frontmatter: str) -> str:
    """Pull the title value out of YAML frontmatter (simple regex, no PyYAML)."""
    m = _TITLE_RE.search(frontmatter)
    return m.group(1).strip() if m else ""


def _word_count(text: str) -> int:
    """Count words in a body string. CJK characters counted individually."""
    cleaned = re.sub(r"[#\[\]()>*_~`|]", " ", text)
    cjk_chars = len(re.findall(r'[\u4e00-\u9fff]', cleaned))
    non_cjk = re.sub(r'[\u4e00-\u9fff]', ' ', cleaned)
    en_words = len(non_cjk.split())
    return cjk_chars + en_words


def _section_text(body: str, heading: str) -> str | None:
    """Extract text under a ## heading until the next ## or EOF.

    Returns None if the heading does not exist.
    """
    pattern = re.compile(
        rf"^##\s+{re.escape(heading)}\s*\n(.*?)(?=^##\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    m = pattern.search(body)
    if m:
        return m.group(1).strip()
    return None


# ---------------------------------------------------------------------------
# Gap scanners
# ---------------------------------------------------------------------------


def scan_pending_questions(questions: list[dict]) -> None:
    """Priority 0: Pending questions from auto-captured sessions.

    Scans all wiki/sources/ pages for a `pending_questions` YAML field
    in frontmatter. These are questions generated by the preference
    tagging system in auto-ingest.py.
    """
    sources_dir = WIKI_ROOT / "sources"
    if not sources_dir.is_dir():
        return

    pq_block_re = re.compile(
        r'^pending_questions:\s*\n((?:\s+-\s+.+\n?)*)',
        re.MULTILINE,
    )
    item_re = re.compile(r'^\s+-\s+"(.+?)"', re.MULTILINE)

    for path in sorted(sources_dir.glob("*.md")):
        text = _read_file(path)
        if text is None:
            continue

        fm, _ = _strip_frontmatter(text)
        block_match = pq_block_re.search(fm)
        if not block_match:
            continue

        block = block_match.group(1)
        for m in item_re.finditer(block):
            question_text = m.group(1)
            questions.append({
                "type": "pending_question",
                "source": path.stem,
                "source_path": str(path.relative_to(WIKI_ROOT)),
                "question": question_text,
                "priority": 0,
            })


def _extract_updated(frontmatter: str) -> str | None:
    """Pull the updated date from YAML frontmatter."""
    m = _UPDATED_RE.search(frontmatter)
    return m.group(1) if m else None


def _extract_source_slugs(frontmatter: str) -> list[str]:
    """Pull source slugs from the sources array in frontmatter."""
    m = _SOURCES_RE.search(frontmatter)
    if not m:
        return []
    raw = m.group(1)
    return [s.strip().strip('"').strip("'") for s in raw.split(",") if s.strip()]


def _latest_source_date(source_slugs: list[str]) -> tuple[str | None, str | None]:
    """Find the most recent updated date among source files.

    Returns (date_string, slug) for the most recently updated source,
    or (None, None) if no source files have a parseable date.
    """
    sources_dir = WIKI_ROOT / "sources"
    latest = None
    latest_slug = None
    for slug in source_slugs:
        path = sources_dir / f"{slug}.md"
        text = _read_file(path)
        if text is None:
            continue
        fm, _ = _strip_frontmatter(text)
        date = _extract_updated(fm)
        if date and (latest is None or date > latest):
            latest = date
            latest_slug = slug
    return latest, latest_slug


def scan_stale_concepts(questions: list[dict]) -> None:
    """Priority 1: Concepts whose understanding hasn't caught up with evidence.

    A concept is stale when its `updated` date is older than the `updated`
    date of its most recent source by more than STALE_THRESHOLD_DAYS.
    Inspired by GBrain's "compiled truth older than latest timeline" alert.
    """
    concepts_dir = WIKI_ROOT / "concepts"
    if not concepts_dir.is_dir():
        return

    threshold = timedelta(days=STALE_THRESHOLD_DAYS)

    for path in sorted(concepts_dir.glob("*.md")):
        text = _read_file(path)
        if text is None:
            continue

        fm, body = _strip_frontmatter(text)
        title = _extract_title(fm) or path.stem
        concept_updated = _extract_updated(fm)
        source_slugs = _extract_source_slugs(fm)

        if not concept_updated or len(source_slugs) < 1:
            continue

        latest_date, latest_slug = _latest_source_date(source_slugs)
        if not latest_date:
            continue

        try:
            concept_dt = datetime.strptime(concept_updated, "%Y-%m-%d")
            source_dt = datetime.strptime(latest_date, "%Y-%m-%d")
        except ValueError:
            continue

        if source_dt - concept_dt > threshold:
            days_behind = (source_dt - concept_dt).days
            questions.append({
                "type": "stale_concept",
                "source": path.stem,
                "concept_path": str(path.relative_to(WIKI_ROOT)),
                "latest_source": latest_slug,
                "question": (
                    f"'{title}' 的理解（{concept_updated}）落后于最新证据"
                    f"（{latest_date}）{days_behind} 天。"
                    f"新的 source 是否改变了你对这个概念的理解？需要重写 Overview 吗？"
                ),
                "priority": 1,
            })


def scan_open_questions(questions: list[dict]) -> None:
    """Gap Type 1: Open Questions from concept pages."""
    concepts_dir = WIKI_ROOT / "concepts"
    if not concepts_dir.is_dir():
        return

    for path in sorted(concepts_dir.glob("*.md")):
        text = _read_file(path)
        if text is None:
            continue

        _, body = _strip_frontmatter(text)
        section = _section_text(body, "Open Questions")
        if section is None:
            continue

        for line in section.splitlines():
            line = line.strip()
            # Accept lines starting with - or *
            if not (line.startswith("- ") or line.startswith("* ")):
                continue
            bullet = line[2:].strip()
            if len(bullet) < 10:
                continue
            questions.append({
                "type": "open_question",
                "source": path.stem,
                "question": bullet,
                "priority": 1,
            })


def scan_thin_pages(questions: list[dict]) -> None:
    """Gap Type 2: Pages with fewer than 100 words."""
    for subdir in ("concepts", "entities"):
        directory = WIKI_ROOT / subdir
        if not directory.is_dir():
            continue

        for path in sorted(directory.glob("*.md")):
            text = _read_file(path)
            if text is None:
                continue

            fm, body = _strip_frontmatter(text)
            title = _extract_title(fm) or path.stem
            wc = _word_count(body)

            if wc < 100:
                questions.append({
                    "type": "thin_page",
                    "source": path.stem,
                    "question": (
                        f"Wiki 里关于'{title}'的记录很少（{wc} 词）。"
                        f"你能多讲讲这个话题吗？"
                    ),
                    "priority": 2,
                })


def scan_timeline_gaps(questions: list[dict]) -> None:
    """Gap Type 3: Months with fewer than 5 source entries."""
    sources_dir = WIKI_ROOT / "sources"
    if not sources_dir.is_dir():
        return

    month_counts: dict[str, int] = {}
    try:
        entries = list(sources_dir.iterdir())
    except OSError:
        return

    for entry in entries:
        if not entry.name.endswith(".md"):
            continue
        m = _DATE_PREFIX_RE.match(entry.name)
        if m:
            month = m.group(1)  # "YYYY-MM"
            month_counts[month] = month_counts.get(month, 0) + 1

    for month in sorted(month_counts):
        count = month_counts[month]
        if count < 5:
            questions.append({
                "type": "timeline_gap",
                "source": f"sources/{month}",
                "question": (
                    f"{month} 这个月的记录比较少（只有 {count} 条）。"
                    f"那段时间你在做什么？"
                ),
                "priority": 3,
            })


def scan_vague_entities(questions: list[dict]) -> None:
    """Gap Type 4: Entity pages with empty/thin Mentions section."""
    entities_dir = WIKI_ROOT / "entities"
    if not entities_dir.is_dir():
        return

    for path in sorted(entities_dir.glob("*.md")):
        text = _read_file(path)
        if text is None:
            continue

        fm, body = _strip_frontmatter(text)
        title = _extract_title(fm) or path.stem

        mentions = _section_text(body, "Mentions")
        # If section doesn't exist or is very short
        if mentions is not None and len(mentions) >= 50:
            continue
        # Only flag if there IS a Mentions heading but it's thin,
        # OR if there's no Mentions heading at all
        questions.append({
            "type": "vague_entity",
            "source": path.stem,
            "question": (
                f"你多次提到 {title}，但 wiki 里关于你们关系的描述不太详细。"
                f"你们是怎么认识的？"
            ),
            "priority": 2,
        })


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    questions: list[dict] = []

    scan_pending_questions(questions)
    scan_stale_concepts(questions)
    scan_open_questions(questions)
    scan_thin_pages(questions)
    scan_timeline_gaps(questions)
    scan_vague_entities(questions)

    # Stable sort by priority (ascending — 0 = highest priority)
    questions.sort(key=lambda q: q["priority"])

    json.dump(questions, sys.stdout, ensure_ascii=False, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
